### ISSUE TITLE
improve request handling

### ISSUE THREAD

**Issue by schTi** [hyrise/Cockpit#231]
**Is your feature request related to a problem? Please describe:**  
Currently we are sending requests for every metric and every db instance. That is not necessary, because we get the data for all instances just by one request. Thats why we should reduce the request frequency and see if the performance issues are may fixed by that change.

**Please describe the solution you'd like:**  
We should use singletons for every metric, like database service. The metric components should then use the data of the singleton. Additionally ensure that requests are only sent when the data is needed. Think about how to handle breaking the request loop, when data isnt needed anymore, and which component should be aware of looping and starting the requests.

**Notes**
Maybe we can find a reasonable pattern to handle this.

**TODOs**
- [x] add eventbus to project
- [x] add metric controller instance as unique singleton handling all requests
- [x] add fetch service of every metric as singleton inside the controller singleton
- [x] metric components are listening to the specific data provided by metric controller
- [x] metrics/views are sending an event with the metrics they need data from
- [x] controller is responsible for looping requests for the specified data, until a new 'metric changed' event with the new needed metrics is emitted
- [x] add functions for start and stop intervals of the specified metrics
- [x] add skeleton loaders

**Affected Component(s):**  
`Frontend`
