### ISSUE TITLE
improve frontend test coverage

### ISSUE THREAD

**Issue by schTi** [hyrise/Cockpit#450]
**Is your feature request related to a problem? Please describe:**  
Currently there is just a basic test setup and only database and navigation tests. We should improve this. 

**TODOs**
- [x] add metric tests
- [x] add plugin tests
- [x] add workload monitoring tests
- [x] add workload generation tests
- [x] add basic view tests
- [x] add selection tests

**Affected Component(s):**  
`frontend/tests/e2e`
